global:
  imageTag: 0.5
  env:
    AMQP_HOST: '{{ .Release.Name }}-rabbitmq'
    USER_HOST: '{{ .Release.Name }}-user'
    CART_HOST: '{{ .Release.Name }}-cart'
    CART_ENDPOINT: '{{ .Release.Name }}-cart:8080'
    DB_HOST: '{{ .Release.Name }}-mysql'
    CATALOGUE_HOST: '{{ .Release.Name }}-catalogue'
    REDIS_HOST: '{{ .Release.Name }}-redis-master'
    MONGO_HOST: '{{ .Release.Name }}-mongodb'
    # ratings
    CATALOGUE_URL: 'http://{{ .Release.Name }}-catalogue:8080'
    PDO_URL: 'mysql:host={{ .Release.Name }}-mysql;dbname=ratings;charset=utf8mb4'
    PHP_HOST: "127.0.0.1"

ingress:
  enabled: true
  className: ""
  # -- ingress `rewrite-target` is needed
  annotations: 
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  host: rs.example.com
  tls: []

mongodb:
  image:
    registry: ghcr.io
    repository: volikon/rs-mongo
    tag: 0.5
  persistence:
    enabled: false
  serviceAccount:
    create: false
  auth:
    enabled: false

redis:
  architecture: standalone
  master:
    persistence:
      enabled: false
  serviceAccount:
    create: false
  auth:
    enabled: false

mysql:
  image:
    registry: ghcr.io
    repository: volikon/rs-mysql
    tag: 0.5
  auth:
    database: cities
    username: shipping
    password: secret
  primary:
    persistence:
      enabled: false
  serviceAccount:
    create: false

rabbitmq:
  auth: 
    username: guest
    password: guest
  clustering:
    enabled: false
  persistence:
    enabled: false
  serviceAccount:
    create: false
  rbac:
    create: false

web:
  image:
    repository: ghcr.io/volikon/rs-web

user:
  image:
    repository: ghcr.io/volikon/rs-user
  probe:
    path: "/health"

catalogue:
  image:
    repository: ghcr.io/volikon/rs-catalogue
  probe:
    path: "/health"

cart:
  image:
    repository: ghcr.io/volikon/rs-cart
  probe:
    path: "/health"

shipping:
  image: 
    repository: ghcr.io/volikon/rs-shipping
  probe:
    path: "/health"

ratings:
  image: 
    repository: ghcr.io/volikon/rs-ratings-nginx
  seconderyContainer:
    name: php
    enabled: true
    image: 
      repository: ghcr.io/volikon/rs-ratings-php
  probe:
    path: "/_health"
  
payment:
  image: 
    repository: ghcr.io/volikon/rs-payment
  probe:
    path: "/health"

dispatch:
  image: 
    repository: ghcr.io/volikon/rs-dispatch
  service:
    enabled: false
