FROM nginx:1.23.3-alpine

RUN apk add --no-cache curl

EXPOSE 80

ENV PHP_HOST=ratings-php

COPY entrypoint.sh /docker-entrypoint.d/

COPY default.conf.template /etc/nginx/conf.d/default.conf.template
COPY html /var/www/html
