FROM php:7.4-fpm-alpine3.16

RUN apk add --no-cache curl unzip libzip && \
    apk add --no-cache --virtual .build-deps libzip-dev && \
    docker-php-ext-install pdo_mysql opcache zip && \
    apk del --no-network .build-deps

WORKDIR /var/www/html

COPY html/ /var/www/html

COPY --from=composer /usr/bin/composer /usr/bin/composer
RUN composer install

# This is important. Symfony needs write permissions and we
# dont know the context in which the container will run, i.e.
# which user will be forced from the outside so better play
# safe for this simple demo.
RUN rm -Rf /var/www/var/*
RUN chown -R www-data /var/www
RUN chmod -R 777 /var/www
