version: '3'
services:
  mysql:
    image: ghcr.io/volikon/rs-mysql:0.1
    cap_add:
      - NET_ADMIN
    networks:
      - robot-shop-testing
  ratings-php:
    image: rs-ratings-php:test
    build:
      context: .
      dockerfile: Dockerfile-php
    depends_on:
      - mysql
    environment:
      APP_ENV: prod
    networks:
      - robot-shop-testing
  ratings-nginx:
    image: rs-ratings-nginx:test
    build:
      context: .
      dockerfile: Dockerfile-nginx
    depends_on:
      - mysql
      - ratings-php
    networks:
      - robot-shop-testing

networks:
  robot-shop-testing:
