---
name: "Action: Image Build"

on:
  workflow_call:
    inputs:
      imagesToBuild:
        description: |-
            Pass a json string with the images to build. e.g.:
            ["cart","catalogue","dispatch","payment","ratings","shipping","user"]
        required: false
        type: string
        default: ''

      pushImages:
        required: false
        default: 'false'
        type: string

jobs:
  build:
    name: Build and push
    runs-on: ubuntu-latest
    if: inputs.imagesToBuild != '' && inputs.imagesToBuild != '[]'
    strategy:
      matrix:
        image: ["${{ fromJson(inputs.imagesToBuild) }}"]
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      
      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Setup GHCR
        if: ${{ inputs.pushImages == 'true' }}
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build all platforms
        id: release
        uses: docker/build-push-action@v3
        with:
          context: ${{ matrix.image }}
          file: Dockerfile
          push: ${{ inputs.pushImages == 'true' }}
          tags: |-
            ghcr.io/${{ github.repository_owner }}/rs-${{ matrix.image }}:$TAG
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      - name: Build successful
        id: build-success
        if: ${{ always() && steps.release.outcome == 'success' }}
        run: |-
          echo "message=🎉 ${{ matrix.image }}" >> $GITHUB_OUTPUT
          echo "color=0x00FF00" >> $GITHUB_OUTPUT
      - name: Build failed
        id: build-failed
        if: ${{ always() && (steps.release.outcome == 'failure') }}
        run: |-
          echo "message=💥 ${{ matrix.image }}" >> $GITHUB_OUTPUT
          echo "color=0xFF0000" >> $GITHUB_OUTPUT
  build_success:
    name: Build matrix success
    runs-on: ubuntu-latest
    needs:
      - build
    if: ${{ always() }}
    steps:
      - name: Check build matrix status
        if: ${{ (inputs.imagesToBuild != '' && inputs.imagesToBuild != '[]') && (needs.build.result != 'success') }}
        run: exit 1
