---
name: "Manual Release"

concurrency:
  group: container-release
  cancel-in-progress: false

on:
  workflow_dispatch:
    inputs:
      app:
        description: "App (ex: dispatch), Default: all"
        default: "ALL"
        required: true
      push:
        description: "Push"
        default: "false"
        required: true


jobs:
  generate-build-matrix:
    name: Generate matrix for building images
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.determine-images.outputs.changes }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install tools
        run: sudo apt-get install moreutils jo

      - name: Determine images to build
        id: determine-images
        shell: bash
        run: |
          if [ "${{ inputs.app }}" = "ALL" ]; then
            echo "changes=`echo 'mongo catalogue user cart mysql shipping ratings payment dispatch web' | jo -a`" >> $GITHUB_OUTPUT
          else
            output="[]"
            output="$(jo -a ${{ inputs.app }})"
            echo "changes=${output}" >> $GITHUB_OUTPUT
          fi
  images-build:
    uses: VoliKoN/robot-shop/.github/workflows/build-images.yml@master
    if: needs.generate-build-matrix.outputs.matrix != '[]'
    needs: ["generate-build-matrix"]
    with:
      imagesToBuild: "${{ needs.generate-build-matrix.outputs.matrix }}"
      pushImages: "${{ github.event.inputs.push }}"
    secrets: inherit
