---
name: Build images on push

concurrency:
  group: container-release
  cancel-in-progress: false

on:
  push:
    branches:
      - 'master'
    paths:
      - 'mongo/**'
      - 'catalogue/**'
      - 'user/**'
      - 'cart/**'
      - 'mysql/**'
      - 'shipping/**'
      - 'ratings/**'
      - 'payment/**'
      - 'dispatch/**'
      - 'web/**'

jobs:
  list-changed-images:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.images.outputs.changes }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.
      - name: Get changed dirs
        id: changed-dirs
        uses: tj-actions/changed-files@v35
        with:
          dir_names: "true"
          dir_names_exclude_root: "true"
          dir_names_max_depth: "1"
          files: |
            mongo/**
            catalogue/**
            user/**
            cart/**
            mysql/**
            shipping/**
            ratings/**
            payment/**
            dispatch/**
            web/**

      - name: List all changed images
        id: images
        run: |
          echo "changes=`echo ${{ steps.changed-dirs.outputs.all_changed_files }} | jq -Rc 'split(" ")'`" >> $GITHUB_OUTPUT
          for dir in ${{ steps.changed-dirs.outputs.all_changed_files }}; do
            echo "$dir $REPO/rs-$dir:$TAG"
          done

  images-build:
    uses: VoliKoN/robot-shop/.github/workflows/build-images.yml@master
    if: needs.list-changed-images.outputs.matrix != '[]'
    needs: ["list-changed-images"]
    with:
      imagesToBuild: "${{ needs.list-changed-images.outputs.matrix }}"
      pushImages: "true"
    secrets: inherit
